name = "china-free-liquidity-panel"
main = "src/worker.js"
compatibility_date = "2026-07-01"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "china-liquidity"
database_id = "填入你的database_id"
